# spring context variables
server:
  port: 4000
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: web-sheet
  main:
    banner-mode: off
  datasource:
    url: jdbc:sqlite:/var/lib/sqlite/data.db
    hikari:
      connection-init-sql: PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=-10000; PRAGMA temp_store=MEMORY;
# end-points
endpoint:
  visitors: api/visitors
# date time formatter
date:
  time:
    format:
      pattern: yyyyMMddHHmmssns
# logging
logging:
  level:
    root: ERROR
    org.springframework.web: WARN
    edu.springoot.organizer: ${LOG_LEVEL:WARN}
    edu.springoot.organizer.data: ${LOG_LEVEL_CON:INFO}
# general variables
lackValue: lack-of-value
cronMonitorDefault: ${CRON:1 2 3 * * *}
cronMonitorCustom: ${CRON_URL_SRC_MONITOR:${cronMonitorDefault}}
# individual comics variables
application:
